-- Agregar columnas de ubicación y contacto a la tabla PLANTAS
-- Ejecutar en Supabase SQL Editor

ALTER TABLE "PLANTAS"
ADD COLUMN IF NOT EXISTS "PAIS" TEXT,
ADD COLUMN IF NOT EXISTS "DEPARTAMENTO" TEXT,
ADD COLUMN IF NOT EXISTS "CIUDAD" TEXT,
ADD COLUMN IF NOT EXISTS "BARRIO" TEXT,
ADD COLUMN IF NOT EXISTS "COMUNA" TEXT,
ADD COLUMN IF NOT EXISTS "CONTACTO" TEXT,
ADD COLUMN IF NOT EXISTS "TELEFONO" TEXT,
ADD COLUMN IF NOT EXISTS "LOCALIZACION" TEXT;

-- Comentarios para documentación
COMMENT ON COLUMN "PLANTAS"."PAIS" IS 'País donde se encuentra la planta';
COMMENT ON COLUMN "PLANTAS"."DEPARTAMENTO" IS 'Departamento o estado';
COMMENT ON COLUMN "PLANTAS"."CIUDAD" IS 'Ciudad';
COMMENT ON COLUMN "PLANTAS"."BARRIO" IS 'Barrio o sector';
COMMENT ON COLUMN "PLANTAS"."COMUNA" IS 'Comuna';
COMMENT ON COLUMN "PLANTAS"."CONTACTO" IS 'Nombre de la persona de contacto';
COMMENT ON COLUMN "PLANTAS"."TELEFONO" IS 'Número de teléfono de contacto';
COMMENT ON COLUMN "PLANTAS"."LOCALIZACION" IS 'Coordenadas GPS o dirección completa';
